version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: ./django-entrypoint.sh
    volumes:
      - .:/code
      - mediac:/code/media
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - dvyy
  db:
    image: postgres
    volumes:
      - data_c:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dvyy
  # uncomment if rstudio is needed
  # rstudio:
  #   build:
  #     context: ./docker/
  #     dockerfile: Dockerfile.rstudio
  #   environment:
  #     - PASSWORD=password
  #   volumes:
  #     - .:/home/rstudio/code
  #     - mediac:/home/rstudio/data
  #   ports:
  #     - 8787:8787
  #   networks:
  #     - dvyy
  plumber:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.plumber
    command: /code/startup.R
    volumes:
      - ./Rsrc:/code
      - mediac:/code/media
    ports:
      - 8181:8181
    networks:
      - dvyy
<<<<<<< HEAD
  pythonslope:
    build:
      context: .
      dockerfile:  ./docker/Dockerfile.pythonslope
    command: python /code/app.py
    volumes:
      - ./Pythonslopesrc:/code
=======
  mean:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mean
    volumes:
>>>>>>> b9857b8de8cc7c82b26b9b88bb926a1a3d497c89
      - mediac:/code/media
    ports:
      - 8080:8080
    networks:
      - dvyy
  pythonservices:
    build:
      context: .
      dockerfile:  ./docker/Dockerfile.pythonservices
    command: python /code/app.py
    volumes:
      - ./Pythonsrc:/code
      - mediac:/code/media
    ports:
      - 5001:5001
    networks:
      - dvyy
  cbinding:
    build:
      context: .
      dockerfile:  ./docker/Dockerfile.c++bind
    command: python /code/c++bind.py
    volumes:
      - ./c++src:/code
      - mediac:/code/media
    ports:
      - 4001:4001
    networks:
      - dvyy
  # java SpringBoot conatiner
  java-springboot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.java-springboot
    volumes:
      - mediac:/code/media
    ports:
      - 8081:8081
    networks:
      - dvyy
networks:
  dvyy:
    driver: bridge
volumes:
  data_c:
  mediac: