version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: ./django-entrypoint.sh
    volumes:
      - .:/code
      - mediac:/code/media
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - dvyy
  db:
    image: postgres
    volumes:
      - data_c:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dvyy
  # uncomment if rstudio is needed
  rstudio:
    build:
      context: ./docker/
      dockerfile: Dockerfile.rstudio
    environment:
      - PASSWORD=password
    volumes:
      - .:/home/rstudio/code
      - mediac:/home/rstudio/data
    ports:
      - 8787:8787
    networks:
      - dvyy
  plumber:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.plumber
    command: /code/startup.R
    volumes:
      - ./Rsrc:/code
      - mediac:/code/media
    ports:
      - 8181:8181
    networks:
      - dvyy
  # java SpringBoot conatiner
  java-springboot:
    build:
      context: ./docker/
      dockerfile: Dockerfile.java-springboot
    volumes:
      - ./java-springboot-src:/code
      - mediac:/code/media
    ports:
      - 8080:8080
    networks:
      - dvyy
networks:
  dvyy:
    driver: bridge
volumes:
  data_c:
  mediac:
