FROM openjdk:8-alpine
WORKDIR ../java-springboot-src/method
RUN echo pwd
RUN mvn package
RUN echo pwd
ARG JAR_FILE= ./target/method-0.0.1-SNAPSHOT.war
COPY ${JAR_FILE} api.war
ENTRYPOINT ["java","-jar","/api.war"]
