#Dockerfile for c++ method

FROM python:latest
LABEL Description="C++ Build Environment"

COPY ./docker/requirementsc++.txt  /tmp

WORKDIR /tmp

RUN pip3 install -r requirementsc++.txt

COPY c++src /code/

ENV HOME /root

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    cmake 

