# Generated by Django 3.2.7 on 2021-12-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0003_rename_datafile_add_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='basic_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='filesize',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='datafile',
            name='num_cols',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='datafile',
            name='num_rows',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
