# Generated by Django 3.2.7 on 2021-12-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0004_auto_20211217_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='basic_processed',
        ),
        migrations.AddField(
            model_name='datafile',
            name='basic_plots',
            field=models.BooleanField(default=False, help_text='Whether basic plots have been created.'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='filesize',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='num_cols',
            field=models.PositiveIntegerField(default=None, help_text='Number of columns in the file.'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='num_rows',
            field=models.PositiveBigIntegerField(default=None, help_text='Number of rows in the file.'),
        ),
    ]
