# Generated by Django 3.2.7 on 2021-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0005_auto_20211217_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='filesize',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='num_cols',
            field=models.PositiveIntegerField(help_text='Number of columns in the file.', null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='num_rows',
            field=models.PositiveBigIntegerField(help_text='Number of rows in the file.', null=True),
        ),
    ]
