# Generated by Django 3.2.7 on 2021-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0006_auto_20211217_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='supported',
            field=models.BooleanField(help_text='Whether the file can be processed.', null=True),
        ),
    ]
