# Generated by Django 3.2.7 on 2021-12-21 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datafiles', '0007_datafile_supported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Method name', max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('prog_language', models.CharField(choices=[('P', 'Python'), ('R', 'R'), ('J', 'Java'), ('JL', 'Julia')], help_text='Programming language in which the method has been implemented', max_length=2)),
                ('end_point', models.CharField(help_text='API call end point', max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='column',
            name='scale',
            field=models.CharField(choices=[('CT', 'Continuous'), ('DS', 'Discrete'), ('OD', 'Ordinal'), ('NM', 'Nominal')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('NM', 'Number'), ('ST', 'String'), ('DT', 'Date'), ('BL', 'Boolean')], max_length=2),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('R', 'Running'), ('S', 'Stopped'), ('C', 'Completed'), ('E', 'Error')], max_length=1)),
                ('datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafiles.datafile')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafiles.method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
