# Generated by Django 3.2.7 on 2021-12-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0008_auto_20211221_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('IN', 'Integer'), ('DB', 'Double'), ('ST', 'String'), ('DT', 'Date'), ('BL', 'Boolean')], max_length=2),
        ),
    ]
