# Generated by Django 3.2.7 on 2021-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0009_alter_column_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='basic_plots',
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_format',
            field=models.TextField(choices=[('CSV', 'Comma-separated values'), ('UNS', 'Unsupported')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
