# Generated by Django 3.2.7 on 2021-12-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0010_auto_20211221_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='type',
            new_name='col_type',
        ),
    ]
