# Generated by Django 3.2.10 on 2021-12-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0011_rename_type_column_col_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='col_type',
            field=models.CharField(choices=[('IN', 'Integer'), ('DB', 'Double'), ('ST', 'String'), ('DT', 'Date'), ('BL', 'Boolean'), ('UK', 'Unknown')], max_length=2),
        ),
    ]
