# Generated by Django 3.2.12 on 2022-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0016_alter_analysis_results_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='col_type',
            field=models.CharField(choices=[('IN', 'Integer'), ('DB', 'Double'), ('ST', 'String'), ('DT', 'Date'), ('BL', 'Boolean'), ('UK', 'Unknown')], max_length=2, null=True),
        ),
    ]
