# Generated by Django 3.2.12 on 2022-02-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0017_alter_column_col_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='parameters',
            field=models.JSONField(help_text='Extra parameters to run the method', null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='doc_file',
            field=models.CharField(help_text='Documentation file of the method, initially, only PDF format is supported', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='json_schema',
            field=models.CharField(help_text='Json-schema file path to validate parameters and generate an html form', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='url_service',
            field=models.CharField(help_text='Url where the taks will run', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='end_point',
            field=models.CharField(help_text='Django API call end point', max_length=1024),
        ),
    ]
