# Generated by Django 3.2.13 on 2022-07-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0019_remove_method_end_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='prog_language',
            field=models.CharField(choices=[('P', 'Python'), ('R', 'R'), ('J', 'Java'), ('JL', 'Julia'), ('KT', 'Kotlin')], help_text='Programming language in which the method has been implemented', max_length=2),
        ),
    ]
